import React, { useEffect } from 'react';

const defaultTitle = 'SimpliKitt - Instant, No-Cost Digital Tools';
const defaultDescription = 'A web-based suite of free, instant, and privacy-first digital tools. All tools run exclusively in your browser, ensuring your data remains private. SimpliKitt offers simple solutions for common digital problems without requiring software installation or account creation.';

const PrivacyPolicyPage: React.FC = () => {
  useEffect(() => {
    const title = 'Privacy Policy - SimpliKitt';
    const description = 'Read the SimpliKitt privacy policy. Learn how we handle your data (or rather, how we don\'t) with our client-side tools.';
    document.title = title;
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', description);
    }
    
    return () => {
      document.title = defaultTitle;
      const metaDescription = document.querySelector('meta[name="description"]');
      if (metaDescription) {
        metaDescription.setAttribute('content', defaultDescription);
      }
    };
  }, []);

  return (
    <div className="max-w-3xl mx-auto py-12">
      <h1 className="text-4xl font-extrabold text-gray-900 text-center">Privacy Policy</h1>
      <div className="mt-8 prose prose-lg text-gray-700 mx-auto">
        <h2 className="text-2xl font-bold mt-8">Introduction</h2>
        <p>
          SimpliKitt ("we", "our", "us") is committed to protecting your privacy. This Privacy Policy explains how your information is handled when you use our website. Since all our tools run client-side in your browser, our data handling practices are minimal.
        </p>

        <h2 className="text-2xl font-bold mt-8">Information We Don't Collect</h2>
        <p>
          Because our tools operate entirely within your web browser:
        </p>
        <ul>
            <li>We do not collect, store, or transmit any data you input into our tools.</li>
            <li>We do not collect, store, or transmit any files you upload to our tools.</li>
            <li>We do not have access to the results or outputs generated by our tools.</li>
        </ul>
        <p>
            Your data remains on your device and is processed locally. It never reaches our servers.
        </p>
        
        <h2 className="text-2xl font-bold mt-8">Information We May Collect</h2>
        <p>
          We may use standard web analytics services (like Google Analytics) to collect anonymous usage data to help us improve our website. This data may include:
        </p>
        <ul>
            <li>The pages you visit on our site.</li>
            <li>The time you spend on each page.</li>
            <li>The type of browser and operating system you are using.</li>
            <li>General geographic location (e.g., country or city).</li>
        </ul>
        <p>This information is aggregated and cannot be used to identify you personally. We use this data solely to understand how users interact with our site and to make improvements.</p>
        
        <h2 className="text-2xl font-bold mt-8">Cookies</h2>
        <p>
          We may use cookies for analytics and to improve your experience. Cookies are small text files stored on your device. You can disable cookies in your browser settings, but this may affect the functionality of some websites.
        </p>

        <h2 className="text-2xl font-bold mt-8">Third-Party Services</h2>
        <p>
            Our website may contain links to other websites. We are not responsible for the privacy practices of these other sites. We encourage you to be aware when you leave our site and to read the privacy statements of each website that collects personally identifiable information.
        </p>

        <h2 className="text-2xl font-bold mt-8">Changes to This Privacy Policy</h2>
        <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
        </p>

        <h2 className="text-2xl font-bold mt-8">Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, please contact us.</p>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;